[tool.poetry]
name = "hanoitower"
version = "0.1.0"
description = ""
authors = ["wayne <kuderge2002@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
